name: Deploy developer.setable.io (mkdocs material based with github pages)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: install
        run: pip install -r requirements.txt

      - name: version
        run: mkdocs --version

      - name: build
        run: mkdocs build --strict --verbose

      - name: gh-deploy
        if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
